environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "1.0"
    - nodejs_version: "1.8"
    - nodejs_version: "2.0"
    - nodejs_version: "2.3"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm rm --save-dev connect-redis
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run test-ci
version: "{build}"
